# Generated by Django 5.1.4 on 2024-12-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_majorspecialization_minorspecialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minorspecialization',
            name='major_specialization',
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MajorSpecialization',
        ),
        migrations.DeleteModel(
            name='MinorSpecialization',
        ),
    ]
